name: Build And Tests
on:
  push:
    branches:
      - "**"

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    container: ddemoniere/zx:19.5.0-bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies --prefer-offline

      - name: Build
        run: pnpm run build

      - name: Run tests
        run: pnpm run test

      - name: Save Build
        if: github.ref_name == github.event.repository.default_branch
        uses: actions/cache/save@v3
        with:
          path: |
            build
          key: ${{ runner.os }}-build-${{ github.ref_name }}-${{ github.sha }}
